apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: demo-cluster
spec:
  version: 7.13.4
  nodeSets:
  - name: hot
    count: 1
    config:
      node.store.allow_mmap: false
      node.roles: [ data_hot, master, ingest, remote_cluster_client, data_content ]
    podTemplate:
      spec:
        containers:
        - name: elasticsearch   
          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - /mnt/elastic-internal/scripts/readiness-probe-script.sh
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 12
            successThreshold: 1
            timeoutSeconds: 12
          env:
          - name: READINESS_PROBE_TIMEOUT
            value: "10"  
          resources:
            limits:
              memory: 25Mi
              cpu: 70m
            requests:
              memory: 25Mi
              cpu: 70m               
        tolerations:
        - effect: NoSchedule
          key: affinity
          value: elastic-hot
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi  
  - name: warm
    count: 1
    config:
      node.store.allow_mmap: false
      node.roles: [ data_warm, master, ingest, remote_cluster_client ]
    podTemplate:
      spec:
        containers:
        - name: elasticsearch   
          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - /mnt/elastic-internal/scripts/readiness-probe-script.sh
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 12
            successThreshold: 1
            timeoutSeconds: 12
          env:
          - name: READINESS_PROBE_TIMEOUT
            value: "10"    
          resources:
            limits:
              memory: 25Mi
              cpu: 70m
            requests:
              memory: 25Mi
              cpu: 70m    
        tolerations:
        - effect: NoSchedule
          key: affinity
          value: elastic-warm
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi   
  - name: cold
    count: 1
    config:
      node.store.allow_mmap: false
      node.roles: [ data_cold, master, ingest, remote_cluster_client ]   
    podTemplate:
      spec:
        containers:
        - name: elasticsearch  
          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - /mnt/elastic-internal/scripts/readiness-probe-script.sh
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 12
            successThreshold: 1
            timeoutSeconds: 12
          env:
          - name: READINESS_PROBE_TIMEOUT
            value: "10"      
          resources:
            limits:
              memory: 25Mi
              cpu: 70m
            requests:
              memory: 25Mi
              cpu: 70m     
        tolerations:
        - effect: NoSchedule
          key: affinity
          value: elastic-cold
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi     